package pulseanddecibels.jp.yamatenki.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AREA.
 */
public class Area {

    private Long id;
    private String name;

    public Area() {
    }

    public Area(Long id) {
        this.id = id;
    }

    public Area(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
