package pulseanddecibels.jp.yamatenki.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHECK_LIST_ITEM.
 */
public class CheckListItem {

    private Long id;
    private String text;
    private Boolean checked;

    public CheckListItem() {
    }

    public CheckListItem(Long id) {
        this.id = id;
    }

    public CheckListItem(Long id, String text, Boolean checked) {
        this.id = id;
        this.text = text;
        this.checked = checked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Boolean getChecked() {
        return checked;
    }

    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

}
