package pulseanddecibels.jp.yamatenki.database.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        MountainDao.createTable(db, ifNotExists);
        CoordinateDao.createTable(db, ifNotExists);
        ForecastDao.createTable(db, ifNotExists);
        WindAndTemperatureDao.createTable(db, ifNotExists);
        PressureDao.createTable(db, ifNotExists);
        AreaDao.createTable(db, ifNotExists);
        PrefectureDao.createTable(db, ifNotExists);
        MyMountainDao.createTable(db, ifNotExists);
        MyMemoDao.createTable(db, ifNotExists);
        StatusDao.createTable(db, ifNotExists);
        CheckListItemDao.createTable(db, ifNotExists);
        ETagDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        MountainDao.dropTable(db, ifExists);
        CoordinateDao.dropTable(db, ifExists);
        ForecastDao.dropTable(db, ifExists);
        WindAndTemperatureDao.dropTable(db, ifExists);
        PressureDao.dropTable(db, ifExists);
        AreaDao.dropTable(db, ifExists);
        PrefectureDao.dropTable(db, ifExists);
        MyMountainDao.dropTable(db, ifExists);
        MyMemoDao.dropTable(db, ifExists);
        StatusDao.dropTable(db, ifExists);
        CheckListItemDao.dropTable(db, ifExists);
        ETagDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(MountainDao.class);
        registerDaoClass(CoordinateDao.class);
        registerDaoClass(ForecastDao.class);
        registerDaoClass(WindAndTemperatureDao.class);
        registerDaoClass(PressureDao.class);
        registerDaoClass(AreaDao.class);
        registerDaoClass(PrefectureDao.class);
        registerDaoClass(MyMountainDao.class);
        registerDaoClass(MyMemoDao.class);
        registerDaoClass(StatusDao.class);
        registerDaoClass(CheckListItemDao.class);
        registerDaoClass(ETagDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
