package pulseanddecibels.jp.yamatenki.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mountainDaoConfig;
    private final DaoConfig coordinateDaoConfig;
    private final DaoConfig forecastDaoConfig;
    private final DaoConfig areaDaoConfig;
    private final DaoConfig prefectureDaoConfig;
    private final DaoConfig myMountainDaoConfig;
    private final DaoConfig myMemoDaoConfig;
    private final DaoConfig statusDaoConfig;
    private final DaoConfig checkListItemDaoConfig;

    private final MountainDao mountainDao;
    private final CoordinateDao coordinateDao;
    private final ForecastDao forecastDao;
    private final AreaDao areaDao;
    private final PrefectureDao prefectureDao;
    private final MyMountainDao myMountainDao;
    private final MyMemoDao myMemoDao;
    private final StatusDao statusDao;
    private final CheckListItemDao checkListItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mountainDaoConfig = daoConfigMap.get(MountainDao.class).clone();
        mountainDaoConfig.initIdentityScope(type);

        coordinateDaoConfig = daoConfigMap.get(CoordinateDao.class).clone();
        coordinateDaoConfig.initIdentityScope(type);

        forecastDaoConfig = daoConfigMap.get(ForecastDao.class).clone();
        forecastDaoConfig.initIdentityScope(type);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        prefectureDaoConfig = daoConfigMap.get(PrefectureDao.class).clone();
        prefectureDaoConfig.initIdentityScope(type);

        myMountainDaoConfig = daoConfigMap.get(MyMountainDao.class).clone();
        myMountainDaoConfig.initIdentityScope(type);

        myMemoDaoConfig = daoConfigMap.get(MyMemoDao.class).clone();
        myMemoDaoConfig.initIdentityScope(type);

        statusDaoConfig = daoConfigMap.get(StatusDao.class).clone();
        statusDaoConfig.initIdentityScope(type);

        checkListItemDaoConfig = daoConfigMap.get(CheckListItemDao.class).clone();
        checkListItemDaoConfig.initIdentityScope(type);

        mountainDao = new MountainDao(mountainDaoConfig, this);
        coordinateDao = new CoordinateDao(coordinateDaoConfig, this);
        forecastDao = new ForecastDao(forecastDaoConfig, this);
        areaDao = new AreaDao(areaDaoConfig, this);
        prefectureDao = new PrefectureDao(prefectureDaoConfig, this);
        myMountainDao = new MyMountainDao(myMountainDaoConfig, this);
        myMemoDao = new MyMemoDao(myMemoDaoConfig, this);
        statusDao = new StatusDao(statusDaoConfig, this);
        checkListItemDao = new CheckListItemDao(checkListItemDaoConfig, this);

        registerDao(Mountain.class, mountainDao);
        registerDao(Coordinate.class, coordinateDao);
        registerDao(Forecast.class, forecastDao);
        registerDao(Area.class, areaDao);
        registerDao(Prefecture.class, prefectureDao);
        registerDao(MyMountain.class, myMountainDao);
        registerDao(MyMemo.class, myMemoDao);
        registerDao(Status.class, statusDao);
        registerDao(CheckListItem.class, checkListItemDao);
    }

    public void clear() {
        mountainDaoConfig.getIdentityScope().clear();
        coordinateDaoConfig.getIdentityScope().clear();
        forecastDaoConfig.getIdentityScope().clear();
        areaDaoConfig.getIdentityScope().clear();
        prefectureDaoConfig.getIdentityScope().clear();
        myMountainDaoConfig.getIdentityScope().clear();
        myMemoDaoConfig.getIdentityScope().clear();
        statusDaoConfig.getIdentityScope().clear();
        checkListItemDaoConfig.getIdentityScope().clear();
    }

    public MountainDao getMountainDao() {
        return mountainDao;
    }

    public CoordinateDao getCoordinateDao() {
        return coordinateDao;
    }

    public ForecastDao getForecastDao() {
        return forecastDao;
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

    public PrefectureDao getPrefectureDao() {
        return prefectureDao;
    }

    public MyMountainDao getMyMountainDao() {
        return myMountainDao;
    }

    public MyMemoDao getMyMemoDao() {
        return myMemoDao;
    }

    public StatusDao getStatusDao() {
        return statusDao;
    }

    public CheckListItemDao getCheckListItemDao() {
        return checkListItemDao;
    }

}
