package pulseanddecibels.jp.yamatenki.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mountainDaoConfig;
    private final DaoConfig coordinateDaoConfig;
    private final DaoConfig areaDaoConfig;
    private final DaoConfig forecastDaoConfig;

    private final MountainDao mountainDao;
    private final CoordinateDao coordinateDao;
    private final AreaDao areaDao;
    private final ForecastDao forecastDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mountainDaoConfig = daoConfigMap.get(MountainDao.class).clone();
        mountainDaoConfig.initIdentityScope(type);

        coordinateDaoConfig = daoConfigMap.get(CoordinateDao.class).clone();
        coordinateDaoConfig.initIdentityScope(type);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        forecastDaoConfig = daoConfigMap.get(ForecastDao.class).clone();
        forecastDaoConfig.initIdentityScope(type);

        mountainDao = new MountainDao(mountainDaoConfig, this);
        coordinateDao = new CoordinateDao(coordinateDaoConfig, this);
        areaDao = new AreaDao(areaDaoConfig, this);
        forecastDao = new ForecastDao(forecastDaoConfig, this);

        registerDao(Mountain.class, mountainDao);
        registerDao(Coordinate.class, coordinateDao);
        registerDao(Area.class, areaDao);
        registerDao(Forecast.class, forecastDao);
    }
    
    public void clear() {
        mountainDaoConfig.getIdentityScope().clear();
        coordinateDaoConfig.getIdentityScope().clear();
        areaDaoConfig.getIdentityScope().clear();
        forecastDaoConfig.getIdentityScope().clear();
    }

    public MountainDao getMountainDao() {
        return mountainDao;
    }

    public CoordinateDao getCoordinateDao() {
        return coordinateDao;
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

    public ForecastDao getForecastDao() {
        return forecastDao;
    }

}
