package pulseanddecibels.jp.yamatenki.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MOUNTAIN.
*/
public class MountainDao extends AbstractDao<Mountain, Long> {

    public static final String TABLENAME = "MOUNTAIN";

    /**
     * Properties of entity Mountain.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property KanjiName = new Property(1, String.class, "kanjiName", false, "KANJI_NAME");
        public final static Property KanjiNameArea = new Property(2, String.class, "kanjiNameArea", false, "KANJI_NAME_AREA");
        public final static Property HiraganaName = new Property(3, String.class, "hiraganaName", false, "HIRAGANA_NAME");
        public final static Property RomajiName = new Property(4, String.class, "romajiName", false, "ROMAJI_NAME");
        public final static Property Height = new Property(5, Integer.class, "height", false, "HEIGHT");
        public final static Property PrefectureId = new Property(6, long.class, "prefectureId", false, "PREFECTURE_ID");
        public final static Property AreaId = new Property(7, long.class, "areaId", false, "AREA_ID");
        public final static Property CoordinateId = new Property(8, long.class, "coordinateId", false, "COORDINATE_ID");
        public final static Property ClosestTown = new Property(9, String.class, "closestTown", false, "CLOSEST_TOWN");
    };

    private DaoSession daoSession;


    public MountainDao(DaoConfig config) {
        super(config);
    }
    
    public MountainDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MOUNTAIN' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'KANJI_NAME' TEXT," + // 1: kanjiName
                "'KANJI_NAME_AREA' TEXT," + // 2: kanjiNameArea
                "'HIRAGANA_NAME' TEXT," + // 3: hiraganaName
                "'ROMAJI_NAME' TEXT," + // 4: romajiName
                "'HEIGHT' INTEGER," + // 5: height
                "'PREFECTURE_ID' INTEGER NOT NULL ," + // 6: prefectureId
                "'AREA_ID' INTEGER NOT NULL ," + // 7: areaId
                "'COORDINATE_ID' INTEGER NOT NULL ," + // 8: coordinateId
                "'CLOSEST_TOWN' TEXT);"); // 9: closestTown
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MOUNTAIN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Mountain entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String kanjiName = entity.getKanjiName();
        if (kanjiName != null) {
            stmt.bindString(2, kanjiName);
        }
 
        String kanjiNameArea = entity.getKanjiNameArea();
        if (kanjiNameArea != null) {
            stmt.bindString(3, kanjiNameArea);
        }
 
        String hiraganaName = entity.getHiraganaName();
        if (hiraganaName != null) {
            stmt.bindString(4, hiraganaName);
        }
 
        String romajiName = entity.getRomajiName();
        if (romajiName != null) {
            stmt.bindString(5, romajiName);
        }
 
        Integer height = entity.getHeight();
        if (height != null) {
            stmt.bindLong(6, height);
        }
        stmt.bindLong(7, entity.getPrefectureId());
        stmt.bindLong(8, entity.getAreaId());
        stmt.bindLong(9, entity.getCoordinateId());
 
        String closestTown = entity.getClosestTown();
        if (closestTown != null) {
            stmt.bindString(10, closestTown);
        }
    }

    @Override
    protected void attachEntity(Mountain entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Mountain readEntity(Cursor cursor, int offset) {
        Mountain entity = new Mountain( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // kanjiName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // kanjiNameArea
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // hiraganaName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // romajiName
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // height
            cursor.getLong(offset + 6), // prefectureId
            cursor.getLong(offset + 7), // areaId
            cursor.getLong(offset + 8), // coordinateId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // closestTown
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Mountain entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKanjiName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setKanjiNameArea(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHiraganaName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRomajiName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHeight(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setPrefectureId(cursor.getLong(offset + 6));
        entity.setAreaId(cursor.getLong(offset + 7));
        entity.setCoordinateId(cursor.getLong(offset + 8));
        entity.setClosestTown(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Mountain entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Mountain entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAreaDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPrefectureDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getCoordinateDao().getAllColumns());
            builder.append(" FROM MOUNTAIN T");
            builder.append(" LEFT JOIN AREA T0 ON T.'AREA_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PREFECTURE T1 ON T.'PREFECTURE_ID'=T1.'_id'");
            builder.append(" LEFT JOIN COORDINATE T2 ON T.'COORDINATE_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Mountain loadCurrentDeep(Cursor cursor, boolean lock) {
        Mountain entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Area area = loadCurrentOther(daoSession.getAreaDao(), cursor, offset);
         if(area != null) {
            entity.setArea(area);
        }
        offset += daoSession.getAreaDao().getAllColumns().length;

        Prefecture prefecture = loadCurrentOther(daoSession.getPrefectureDao(), cursor, offset);
         if(prefecture != null) {
            entity.setPrefecture(prefecture);
        }
        offset += daoSession.getPrefectureDao().getAllColumns().length;

        Coordinate coordinate = loadCurrentOther(daoSession.getCoordinateDao(), cursor, offset);
         if(coordinate != null) {
            entity.setCoordinate(coordinate);
        }

        return entity;    
    }

    public Mountain loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Mountain> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Mountain> list = new ArrayList<Mountain>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Mountain> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Mountain> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
