package pulseanddecibels.jp.yamatenki.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MOUNTAIN.
*/
public class MountainDao extends AbstractDao<Mountain, Long> {

    public static final String TABLENAME = "MOUNTAIN";

    /**
     * Properties of entity Mountain.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Yid = new Property(1, String.class, "yid", false, "YID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property TitleExt = new Property(3, String.class, "titleExt", false, "TITLE_EXT");
        public final static Property TitleEnglish = new Property(4, String.class, "titleEnglish", false, "TITLE_ENGLISH");
        public final static Property Kana = new Property(5, String.class, "kana", false, "KANA");
        public final static Property ReferenceCity = new Property(6, String.class, "referenceCity", false, "REFERENCE_CITY");
        public final static Property PrefectureId = new Property(7, long.class, "prefectureId", false, "PREFECTURE_ID");
        public final static Property AreaId = new Property(8, long.class, "areaId", false, "AREA_ID");
        public final static Property Height = new Property(9, Integer.class, "height", false, "HEIGHT");
        public final static Property TopMountain = new Property(10, Boolean.class, "topMountain", false, "TOP_MOUNTAIN");
    }

    private DaoSession daoSession;


    public MountainDao(DaoConfig config) {
        super(config);
    }
    
    public MountainDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MOUNTAIN' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'YID' TEXT," + // 1: yid
                "'TITLE' TEXT," + // 2: title
                "'TITLE_EXT' TEXT," + // 3: titleExt
                "'TITLE_ENGLISH' TEXT," + // 4: titleEnglish
                "'KANA' TEXT," + // 5: kana
                "'REFERENCE_CITY' TEXT," + // 6: referenceCity
                "'PREFECTURE_ID' INTEGER NOT NULL ," + // 7: prefectureId
                "'AREA_ID' INTEGER NOT NULL ," + // 8: areaId
                "'HEIGHT' INTEGER," + // 9: height
                "'TOP_MOUNTAIN' INTEGER);"); // 10: topMountain
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MOUNTAIN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Mountain entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String yid = entity.getYid();
        if (yid != null) {
            stmt.bindString(2, yid);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String titleExt = entity.getTitleExt();
        if (titleExt != null) {
            stmt.bindString(4, titleExt);
        }
 
        String titleEnglish = entity.getTitleEnglish();
        if (titleEnglish != null) {
            stmt.bindString(5, titleEnglish);
        }
 
        String kana = entity.getKana();
        if (kana != null) {
            stmt.bindString(6, kana);
        }
 
        String referenceCity = entity.getReferenceCity();
        if (referenceCity != null) {
            stmt.bindString(7, referenceCity);
        }
        stmt.bindLong(8, entity.getPrefectureId());
        stmt.bindLong(9, entity.getAreaId());
 
        Integer height = entity.getHeight();
        if (height != null) {
            stmt.bindLong(10, height);
        }
 
        Boolean topMountain = entity.getTopMountain();
        if (topMountain != null) {
            stmt.bindLong(11, topMountain ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(Mountain entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Mountain readEntity(Cursor cursor, int offset) {
        Mountain entity = new Mountain( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // yid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // titleExt
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // titleEnglish
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // kana
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // referenceCity
            cursor.getLong(offset + 7), // prefectureId
            cursor.getLong(offset + 8), // areaId
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // height
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0 // topMountain
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Mountain entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setYid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitleExt(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitleEnglish(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setKana(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setReferenceCity(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPrefectureId(cursor.getLong(offset + 7));
        entity.setAreaId(cursor.getLong(offset + 8));
        entity.setHeight(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setTopMountain(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Mountain entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Mountain entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAreaDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPrefectureDao().getAllColumns());
            builder.append(" FROM MOUNTAIN T");
            builder.append(" LEFT JOIN AREA T0 ON T.'AREA_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PREFECTURE T1 ON T.'PREFECTURE_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Mountain loadCurrentDeep(Cursor cursor, boolean lock) {
        Mountain entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Area area = loadCurrentOther(daoSession.getAreaDao(), cursor, offset);
         if(area != null) {
            entity.setArea(area);
        }
        offset += daoSession.getAreaDao().getAllColumns().length;

        Prefecture prefecture = loadCurrentOther(daoSession.getPrefectureDao(), cursor, offset);
         if(prefecture != null) {
            entity.setPrefecture(prefecture);
        }

        return entity;    
    }

    public Mountain loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Mountain> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Mountain> list = new ArrayList<Mountain>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Mountain> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Mountain> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
