package pulseanddecibels.jp.yamatenki.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PRESSURE.
*/
public class PressureDao extends AbstractDao<Pressure, Long> {

    public static final String TABLENAME = "PRESSURE";

    /**
     * Properties of entity Pressure.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Height = new Property(1, Integer.class, "height", false, "HEIGHT");
        public final static Property Pressure = new Property(2, Integer.class, "pressure", false, "PRESSURE");
        public final static Property MountainId = new Property(3, long.class, "mountainId", false, "MOUNTAIN_ID");
    }

    private DaoSession daoSession;

    private Query<Pressure> mountain_PressureListQuery;

    public PressureDao(DaoConfig config) {
        super(config);
    }
    
    public PressureDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PRESSURE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'HEIGHT' INTEGER," + // 1: height
                "'PRESSURE' INTEGER," + // 2: pressure
                "'MOUNTAIN_ID' INTEGER NOT NULL );"); // 3: mountainId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PRESSURE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Pressure entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer height = entity.getHeight();
        if (height != null) {
            stmt.bindLong(2, height);
        }
 
        Integer pressure = entity.getPressure();
        if (pressure != null) {
            stmt.bindLong(3, pressure);
        }
        stmt.bindLong(4, entity.getMountainId());
    }

    @Override
    protected void attachEntity(Pressure entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Pressure readEntity(Cursor cursor, int offset) {
        Pressure entity = new Pressure( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // height
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // pressure
            cursor.getLong(offset + 3) // mountainId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Pressure entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHeight(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPressure(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setMountainId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Pressure entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Pressure entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "pressureList" to-many relationship of Mountain. */
    public List<Pressure> _queryMountain_PressureList(long mountainId) {
        synchronized (this) {
            if (mountain_PressureListQuery == null) {
                QueryBuilder<Pressure> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MountainId.eq(null));
                mountain_PressureListQuery = queryBuilder.build();
            }
        }
        Query<Pressure> query = mountain_PressureListQuery.forCurrentThread();
        query.setParameter(0, mountainId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMountainDao().getAllColumns());
            builder.append(" FROM PRESSURE T");
            builder.append(" LEFT JOIN MOUNTAIN T0 ON T.'MOUNTAIN_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Pressure loadCurrentDeep(Cursor cursor, boolean lock) {
        Pressure entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Mountain mountain = loadCurrentOther(daoSession.getMountainDao(), cursor, offset);
         if(mountain != null) {
            entity.setMountain(mountain);
        }

        return entity;    
    }

    public Pressure loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Pressure> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Pressure> list = new ArrayList<Pressure>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Pressure> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Pressure> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
